### ISSUE TITLE
您好请教一下报这个错误应该怎么解决

### ISSUE THREAD

**Issue by Zzz-Soar** [pz-white/DrugBAN#1]
![image](https://user-images.githubusercontent.com/57261217/220058197-0f6073cc-5c55-44d8-9905-b1a0a5abaa58.png)

**Comment by peizhenbai** [comment]
Hi, the error shows that the `--cfg` and `--data` arguments are not specified. Could you provide your complete running command for the `main.py`? The two arguments are required for specifying which config file and dataset you want to use. Here is an example:

```
$ python main.py --cfg "configs/DrugBAN.yaml" --data "bindingdb" --split "random"
```
