### ISSUE TITLE
药物分子的最大原子数为什么设置为290？

### ISSUE THREAD

**Issue by Kimmm-pzl** [pz-white/DrugBAN#10]
您好，想向您请教一下为何药物分子的最大原子数设置为290？

**Comment by peizhenbai** [comment]
您好，最大原子数设为290是为了能覆盖实验数据集中所有的药物小分子，使得GCN能编码训练。根据数据集的分子大小统计，也可以对这个超参数进行相应调整

**Comment by Kimmm-pzl** [comment]
感谢您的回复

**Comment by HouXiao11** [comment]
> 您好，想向您请教一下为何药物分子的最大原子数设置为290？

您好，请问您知道为什么蛋白质序列的最大长度设置为1200吗？在实验数据集中有不少蛋白质序列长度已经超过1200。期待您的回复。
