### ISSUE TITLE
Interpretability with bilinear attention visualization

### ISSUE THREAD

**Issue by Kimmm-pzl** [pz-white/DrugBAN#11]
您好，
        我一直在研究您的项目，并且对其中的某些部分有一些疑问，特别是如何通过Attention Map映射到对蛋白结合有贡献的原子。
        具体来说，我注意到您在预处理中添加了虚拟节点，但我不太清楚它们是如何与Attention Map相关联的。是否有特定的方式或算法，您可以向我解释一下吗？  
        我非常感激您的时间和帮助，这将有助于我更深入地理解您的项目。
谢谢！

**Comment by peizhenbai** [comment]
您好，虚拟节点相对于padding embedding，没有实际意义且不参与attention map的计算。使用虚拟节点只是为了方便模型对不同size的数据进行批量训练和矩阵计算

**Comment by Kimmm-pzl** [comment]
感谢您的回复。
