### ISSUE TITLE
i dont konw why

### ISSUE THREAD

**Issue by returnwust** [pz-white/DrugBAN#3]
![}RXG23FIW8AV%MG3LC~1 )L](https://user-images.githubusercontent.com/86417309/228801460-329f927f-d945-4845-a6d9-893170efd54a.png)
![ZQG_XTBGCZ)ENYD)7(XJRUO](https://user-images.githubusercontent.com/86417309/228801474-91cb0c7a-5f5c-433a-aa31-8b11993c42d5.png)

**Comment by peizhenbai** [comment]
Hi, did you follow the installation guide in README? I suggest you create a new conda environment to config the dependencies.
