### ISSUE TITLE
drugban 图神经网络计算

### ISSUE THREAD

**Issue by RuiDr** [pz-white/DrugBAN#4]
你好，我想问下你这个训练拟合，一共训练了多久呀？我看代码里面好像是只有一层gcn？

**Comment by peizhenbai** [comment]
你好，训练拟合的轮次是100个epochs，时长取决于不同数据集大小和实验设置。代码里面是有三层GCN，这里我们使用的是dgllife中的GCN模型，它的层数取决于输入参数的`hidden_feats`的长度，我们的配置`config["DRUG"]["HIDDEN_LAYERS"]`是具有三个的隐藏层大小的列表，所以是一个三层GCN。

**Comment by RuiDr** [comment]
嗯呢，已经知道了，非常感谢!
