### ISSUE TITLE
Question about the size of Human dataset

### ISSUE THREAD

**Issue by QizhiPei** [pz-white/DrugBAN#6]
Hi:

It is really a nice work about DTI.
I'm a little confused by the human dataset in this github repo. `datasets/human/full.csv` has 6728 samples. However, the sum of samples in `train.csv`, `val.csv` and `test.csv` in `datasets/human/random/`  is 5997. 

So are there some special filters for human dataset?

Thanks

**Comment by peizhenbai** [comment]
Hi,

The `full.csv` of Human is the source data from previous work. We found that there were some duplicate DTI rows in it. Therefore, we dropped these duplicates to avoid overlap before the split, resulting in a reduction to 5997. Thank you for pointing it out and I will add a description later.

**Comment by QizhiPei** [comment]
> Hi,
> 
> The `full.csv` of Human is the source data from previous work. We found that there were some duplicate DTI rows in it. Therefore, we dropped these duplicates to avoid overlap before the split, resulting in a reduction to 5997. Thank you for pointing it out and I will add a description later.

Thanks for your reply!
