### ISSUE TITLE
Whether DrugBAN is a trained model

### ISSUE THREAD

**Issue by Huahuatii** [pz-white/DrugBAN#7]
你好~，我想问一下这个DrugBAN是否是一个已经训练好的模型（或者说有训练好的版本），我想要用我自己的蛋白质和分子数据能否直接进行预测是否可行，还是说我应该用一些已知结合情况的数据进行训练才可以使用呢？

**Comment by peizhenbai** [comment]
你好，抱歉最近比较忙未及时回复，我们有提供不同数据集来训练DrugBAN，你需要根据自己需求先训练好模型再进行预测，预测模块代码可以在`trainer.py`中找到，谢谢
