### ISSUE TITLE
你好，请问为什么在test里计算AUC等值时需要引入test dataset的标签来确定threshold_optim值？

### ISSUE THREAD

**Issue by CQ-zhang-2016** [pz-white/DrugBAN#9]
在您的https://github.com/peizhenbai/DrugBAN/blob/9923f8c99959e00263103ff9ac61ba0eaccc8e02/trainer.py#L344 中，使用测试集的标签来确定最佳的thred_optim，这让我感到困惑，我该如何使用DrugBAN推理无标签或标签不准确的数据呢？

**Comment by peizhenbai** [comment]
你好，AUC的计算并没有使用threshold，这里的thred_optim是为了方便计算像Accuracy，Sensitivity等需要二分类的metrics来进行公平的比较，这在其他的基线模型实验中也比较常见。当推理无标签数据时，DrugBAN的预测输出是一个[0,1]的概率值，你可以根据概率值判断置信度，或者自己计算合适的threshold
